name: sync
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "update: Sync legal-dong data" || echo "No changes to commit"
          git push